server:
  port: 8081
  forward-headers-strategy: framework
  servlet:
    context-path: /api

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/connecthub_auth?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 9981
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: satyamsharma000000s@gmail.com
    password: tova bqqb zrnd vszh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
            redirect-uri: "https://13.50.25.162.nip.io/api/auth/oauth2/callback/{registrationId}"
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: user:email
            redirect-uri: "https://13.50.25.162.nip.io/api/auth/oauth2/callback/{registrationId}"

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000
    refresh-expiration-ms: 604800000
  frontend-url: https://connect-hub-frontend-five.vercel.app

  cors:
    allowed-origins: "http://localhost:3000,http://localhost:8080"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.connecthub: DEBUG
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: http://admin:connecthub-eureka-secret@localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    health-check-url-path: /api/actuator/health
    status-page-url-path: /api/actuator/info
