version: "3.9"

services:
  mysql-message:
    image: mysql:8.0
    container_name: connecthub-message-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: connecthub_message
    ports:
      - "3308:3306"
    volumes:
      - message_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  message-service:
    build: .
    container_name: connecthub-message-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-message:3306/connecthub_message?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      APP_JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      APP_ROOM_SERVICE_URL: http://room-service:8082/api
      APP_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:8080"
    depends_on:
      mysql-message:
        condition: service_healthy

volumes:
  message_mysql_data:
