version: "3.9"
services:
  websocket-handler:
    build: .
    container_name: connecthub-websocket
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      APP_JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      APP_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:8080"
      APP_SERVICES_MESSAGE_SERVICE:      http://host.docker.internal:8083/api
      APP_SERVICES_PRESENCE_SERVICE:     http://host.docker.internal:8085/api
      APP_SERVICES_NOTIFICATION_SERVICE: http://host.docker.internal:8087/api
      APP_SERVICES_ROOM_SERVICE:         http://host.docker.internal:8082/api
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://admin:connecthub-eureka-secret@host.docker.internal:8761/eureka/
      SPRING_PROFILES_ACTIVE: prod
